nexus-file-converter:
  debug:
    enabled: false
    suspend: false
  beamline: ckk43848
  template:
    entry/:
      NX_class@: NXentry
      instrument/:
        NX_class@: NXinstrument
        name: ckk43848

  volumes:
  - name: nexus-template
    configMap:
      name: nexus-template
      items:
      - key: template.yaml
        path: template.yaml
  - name: nexus-data
    hostPath:
      path: /dls/ckk43848/data
      type: DirectoryOrCreate

  volumeMounts:
  - name: nexus-data
    mountPath: /dls/ckk43848/data
    mountPropagation: HostToContainer
  - name: nexus-template
    mountPath: /templates

  application:
    server:
      port: 8084
    spring:
      profiles:
        active: rabbitmq
      rabbitmq:
        host: ckk43848-rabbitmq-daq.diamond.ac.uk
        username: guest
        password: guest
    files:
      output:
        # directory:
        #   staticDirectory: /dls/ckk43848/data/2025
        nameTemplate: <DATA_SESSION>
        devices:
          types:
            synchrotron: NX_SOURCE
#  securityContext:
#    runAsUser:
#    runAsGroup:
