blueapi:
  hostNetwork: true
  resources:
    limits:
      cpu: 1000m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 100Mi
  nodeSelector:
    kubernetes.io/hostname: ckk43848-control.diamond.ac.uk
  ingress:
    create: true
    host: ckk43848-blueapi.diamond.ac.uk
  
  worker:
    env:
      metadata:
         instrument: ckk43848
         # instrument_session: 
      sources:
      - kind: dodal
        module: dodal.beamlines.ckk43848
      - kind: planFunctions
        module: dodal.plans
      events:
        broadcast_status_events: false
    stomp:
      auth:
        username: guest
        password: guest
      host: ckk43848-rabbitmq-daq.diamond.ac.uk
      enabled: true
    logging:
      level: "INFO"
      graylog:
        enabled: true
        url: http://graylog-log-target.diamond.ac.uk:12231/
    # oidc:
    #  well_known_url: "https://authn.diamond.ac.uk/realms/master/.well-known/openid-configuration"
    #  client_id: "blueapi-cli"
    scratch:
      root: /dls_sw/ckk43848/software/blueapi/scratch
      repositories:
        - name: dodal
          remote_url: https://github.com/DiamondLightSource/dodal.git
  initContainer:
    enabled: true
